### ISSUE TITLE
Bill of materials

### ISSUE THREAD

**Issue by stylesuxx** [rgbskills/fpv_open_racer#3]
I would re-name the requirements section to "Bill of materials" or BOM and maybe even link to a source to acquire the specific parts (at least those that are not so common, eg. the standoffs).

And by nylon nuts you mean nyloc nuts, no?

I think you also do not mention thickness of top and bottom plate - I assume they should be 2mm?

**Comment by rgbskills** [comment]
Re-naming requirements to "Bill of materials" is a good idea. also, I'm all in on the linking stuff.

here is an example of the nuts I mentioned: https://armattanproductions.com/pages/hardware_details/10/47

I will work on some sort of image that shows assembly and material thickness and I also think we should mention it in the features section.

**Comment by rgbskills** [comment]
Added links, renamed requirements section :)
