### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by stylesuxx** [rgbskills/fpv_open_racer#6]
Is there a slack or similar to gather the community?

**Comment by rgbskills** [comment]
https://join.slack.com/t/openfpvworkspace/shared_invite/enQtODgyMDY0MTgyNDAxLTNkYTExNzY0YzkxYjYwZTdiMzQ1MzkwNzc3OTJhODZiMTdiMTg1ZTQwYjM1NjA1ODZkYjUzNWY0YTA1NTUwZmE

**Comment by rgbskills** [comment]
I just created a slack channel called openfpv, will add a link in the readme :)
