### ISSUE TITLE
carbon fiber direction in render

### ISSUE THREAD

**Issue by stylesuxx** [rgbskills/fpv_open_racer#7]
This will come up at some point - the carbon fiber direction on the arms should go in line with the arms - I mean 45 degrees  rotated to what they are now. I know, it's *just* a render ;-) And I do not know if this is possible at all with your design tool?

**Comment by rgbskills** [comment]
I never played around with materials in fusion360, I will look into it

**Comment by rgbskills** [comment]
Just figured out how to do this. I'm working on it for the next release.
